# Generated by Django 5.1 on 2025-11-28 06:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fundraiser",
            options={"ordering": ["sort_order", "-date_created"]},
        ),
        migrations.RemoveField(
            model_name="fundraiser",
            name="image",
        ),
        migrations.RemoveField(
            model_name="fundraiser",
            name="is_open",
        ),
        migrations.RemoveField(
            model_name="pledge",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="pledge",
            name="pledge_type",
        ),
        migrations.AddField(
            model_name="fundraiser",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="fundraiser",
            name="enable_rewards",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fundraiser",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundraiser",
            name="image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="fundraiser",
            name="location",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="fundraiser",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="fundraiser",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="fundraiser",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pledge",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pledge",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pledge",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fundraiser",
            name="goal",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pledge",
            name="comment",
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name="ItemPledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("donation", "Donation"), ("loan", "Loan")],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "pledge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_detail",
                        to="fundraisers.pledge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoneyPledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("comment", models.TextField(blank=True)),
                (
                    "pledge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_detail",
                        to="fundraisers.pledge",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Need",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "need_type",
                    models.CharField(
                        choices=[
                            ("money", "Money"),
                            ("time", "Time"),
                            ("item", "Item"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("partial", "Partial"),
                            ("filled", "Filled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "fundraiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="needs",
                        to="fundraisers.fundraiser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoneyNeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("comment", models.TextField(blank=True)),
                (
                    "need",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="money_detail",
                        to="fundraisers.need",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pledge",
            name="need",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pledges",
                to="fundraisers.need",
            ),
        ),
        migrations.CreateModel(
            name="RewardTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "min_contribution_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("image_url", models.URLField(blank=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("max_backers", models.IntegerField(blank=True, null=True)),
                (
                    "fundraiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reward_tiers",
                        to="fundraisers.fundraiser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemNeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=200)),
                ("quantity_needed", models.IntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("donation", "Donation"),
                            ("loan", "Loan"),
                            ("either", "Either"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "need",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_detail",
                        to="fundraisers.need",
                    ),
                ),
                (
                    "donation_reward_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donation_item_needs",
                        to="fundraisers.rewardtier",
                    ),
                ),
                (
                    "loan_reward_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_item_needs",
                        to="fundraisers.rewardtier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeNeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("volunteers_needed", models.IntegerField()),
                ("role_title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "need",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_detail",
                        to="fundraisers.need",
                    ),
                ),
                (
                    "reward_tier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="time_needs",
                        to="fundraisers.rewardtier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimePledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                (
                    "hours_committed",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "pledge",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_detail",
                        to="fundraisers.pledge",
                    ),
                ),
            ],
        ),
    ]
