# Generated by Django 5.1 on 2025-12-03 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "fundraisers",
            "0002_alter_fundraiser_options_remove_fundraiser_image_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rewardtier",
            name="min_contribution_value",
        ),
        migrations.AddField(
            model_name="pledge",
            name="reward_tier",
            field=models.ForeignKey(
                blank=True,
                help_text="Which reward this pledge is getting, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pledges",
                to="fundraisers.rewardtier",
            ),
        ),
        migrations.AddField(
            model_name="rewardtier",
            name="minimum_contribution_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum cash amount for this reward (used for money pledges only).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rewardtier",
            name="max_backers",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
