# Generated by Django 5.1 on 2025-12-10 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0003_remove_rewardtier_min_contribution_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rewardtier",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("money", "Money pledge"),
                    ("time", "Time pledge"),
                    ("item", "Item pledge"),
                ],
                default="money",
                help_text="What kind of pledge this reward is for.",
                max_length=10,
            ),
        ),
    ]
