# Generated by Django 5.1 on 2025-12-12 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0004_rewardtier_reward_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FundraiserTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fundraiser_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TemplateNeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "need_type",
                    models.CharField(
                        choices=[
                            ("money", "Money"),
                            ("time", "Time"),
                            ("item", "Item"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("priority", models.IntegerField(default=1)),
                ("sort_order", models.IntegerField(default=1)),
                (
                    "default_status",
                    models.CharField(
                        blank=True,
                        help_text="Optional default status to use when creating the Need (e.g. 'draft').",
                        max_length=50,
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For money needs: target amount.",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "hours_needed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="For time needs: total hours needed.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "quantity_needed",
                    models.IntegerField(
                        blank=True,
                        help_text="For item needs: quantity required.",
                        null=True,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_needs",
                        to="fundraisers.fundraisertemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TemplateRewardTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "minimum_contribution_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Minimum total contribution to earn this tier.",
                        max_digits=10,
                    ),
                ),
                ("image_url", models.URLField(blank=True)),
                ("sort_order", models.IntegerField(default=1)),
                ("max_backers", models.IntegerField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_reward_tiers",
                        to="fundraisers.fundraisertemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "minimum_contribution_value"],
            },
        ),
    ]
