# Generated by Django 5.1 on 2025-12-12 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0005_fundraisertemplate_templateneed_templaterewardtier"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="templaterewardtier",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.RemoveField(
            model_name="templateneed",
            name="default_status",
        ),
        migrations.RemoveField(
            model_name="templateneed",
            name="hours_needed",
        ),
        migrations.AddField(
            model_name="templateneed",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Optional default comment for money needs."
            ),
        ),
        migrations.AddField(
            model_name="templateneed",
            name="donation_reward_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template reward tier for item donations.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donation_item_template_needs",
                to="fundraisers.templaterewardtier",
            ),
        ),
        migrations.AddField(
            model_name="templateneed",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="templateneed",
            name="item_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="templateneed",
            name="loan_reward_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Template reward tier for item loans.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loan_item_template_needs",
                to="fundraisers.templaterewardtier",
            ),
        ),
        migrations.AddField(
            model_name="templateneed",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="templateneed",
            name="mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("donation", "Donation"),
                    ("loan", "Loan"),
                    ("either", "Either"),
                ],
                help_text="Donation / Loan / Either (copied to ItemNeed).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="templateneed",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="templateneed",
            name="role_title",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="templateneed",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="templateneed",
            name="time_reward_template",
            field=models.ForeignKey(
                blank=True,
                help_text="Which template reward tier to use for this time need.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_template_needs",
                to="fundraisers.templaterewardtier",
            ),
        ),
        migrations.AddField(
            model_name="templateneed",
            name="volunteers_needed",
            field=models.IntegerField(
                blank=True, help_text="Number of volunteers required.", null=True
            ),
        ),
        migrations.AddField(
            model_name="templaterewardtier",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("money", "Money pledge"),
                    ("time", "Time pledge"),
                    ("item", "Item pledge"),
                ],
                default="money",
                help_text="What kind of pledge this reward is for.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="templateneed",
            name="need_type",
            field=models.CharField(
                choices=[("money", "Money"), ("time", "Time"), ("item", "Item")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="templateneed",
            name="priority",
            field=models.CharField(
                choices=[("high", "High"), ("medium", "Medium"), ("low", "Low")],
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="templateneed",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="templateneed",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="templaterewardtier",
            name="max_backers",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="templaterewardtier",
            name="minimum_contribution_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum cash amount for this reward (used for money pledges).",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="templaterewardtier",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
