# Generated by Django 5.1 on 2025-12-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0006_alter_templaterewardtier_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundraisertemplate",
            name="enable_rewards",
            field=models.BooleanField(
                default=True,
                help_text="Should this template assume rewards are switched on?",
            ),
        ),
        migrations.AddField(
            model_name="fundraisertemplate",
            name="goal",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Suggested goal amount for this template.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="fundraisertemplate",
            name="location",
            field=models.TextField(
                blank=True,
                help_text="Suggested location text (e.g. 'The Burrow, West End').",
            ),
        ),
        migrations.AddField(
            model_name="fundraisertemplate",
            name="title",
            field=models.CharField(
                default="Untitled Template",
                help_text="Suggested fundraiser title when using this template.",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
