# Generated by Django 5.1 on 2026-02-08 11:27

from django.db import migrations, models


def normalize_need_statuses(apps, schema_editor):
    Need = apps.get_model("fundraisers", "Need")

    # Convert any old "partial" rows to "open"
    Need.objects.filter(status="partial").update(status="open")


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0007_fundraisertemplate_enable_rewards_and_more"),
    ]

    operations = [
        # 1) Data cleanup first (so no rows are left with an invalid choice)
        migrations.RunPython(normalize_need_statuses, migrations.RunPython.noop),

        # 2) Then update the choices / labels
        migrations.AlterField(
            model_name="fundraiser",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft (Unpublished)"),
                    ("active", "Active (Published)"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="need",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("filled", "Filled"),
                    ("closed", "Closed"),
                    ("cancelled", "Cancelled"),
                ],
                default="open",
                max_length=20,
            ),
        ),
    ]
