# Generated by Django 5.1 on 2026-02-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0008_alter_fundraiser_status_alter_need_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundraiser",
            name="require_pledge_approval",
            field=models.BooleanField(default=True),
        ),
    ]
