# Generated by Django 5.1 on 2026-02-13 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraisers", "0009_fundraiser_require_pledge_approval"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeneed",
            name="end_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="timeneed",
            name="start_datetime",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
